//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Valor { get; set; }
        public int fk_usuarios { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
